export const DEVNET_WALLET_A = "4rNYAEukLFs6gB8TVAM1NkBMf1MxKRiZQMNkNiYovHJq";
export const DEVNET_WALLET_B = "3bvvh4hQHmrPBjCCRBbBcqRSCiDkAEQzDGNwjNQLUMJ5";
export const DEVNET_WALLET_C = "7UX2i7SucgLMQcfZ75s3VXmZZY4YRUyJN9X1RgfMoDUi";
export const DEVNET_WALLET_D = "GvDMxPzN1sCj7L26YDK2HnMRXEQmQ2aemov8YBtPS7vR";
export const DEVNET_WALLET_E = "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM";